export enum AccountType {
  USER_AVAILABLE = 'USER_AVAILABLE',
  USER_LOCKED = 'USER_LOCKED',
  SYSTEM_FEE = 'SYSTEM_FEE',
  SYSTEM_HOT_WALLET = 'SYSTEM_HOT_WALLET',
  SYSTEM_COLD_WALLET = 'SYSTEM_COLD_WALLET',
  SYSTEM_EXCHANGE = 'SYSTEM_EXCHANGE',
  SYSTEM_BOT_POOL = 'SYSTEM_BOT_POOL',
}
