export enum RiskRuleType {
  WITHDRAWAL_LIMIT = 'WITHDRAWAL_LIMIT',
  VELOCITY_CHECK = 'VELOCITY_CHECK',
  POSITION_LIMIT = 'POSITION_LIMIT',
  DAILY_LOSS_LIMIT = 'DAILY_LOSS_LIMIT',
  CIRCUIT_BREAKER = 'CIRCUIT_BREAKER',
}
