export enum UserRole {
  GUEST = 'GUEST',
  USER = 'USER',
  VERIFIED_USER = 'VERIFIED_USER',
  ADMIN = 'ADMIN',
  COMPLIANCE_ADMIN = 'COMPLIANCE_ADMIN',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  SUPPORT_ADMIN = 'SUPPORT_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
